name: Coverage

on:
  push:
    branches: [main]

env:
  GIST_ID: d4d99431f51f28cef15d3fe6ab985e4a

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: |
          go test -v -coverprofile=coverage.out -covermode=atomic ./... | tee test.out
          go tool cover -func=coverage.out >> test.out

      - name: Upload badges to Gist
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: ${{ env.GIST_ID }}
          token: ${{ secrets.GIST_TOKEN }}
